{% set version = "2.6.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gld
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gld_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gld/gld_{{ version }}.tar.gz
  sha256: cc6ff7a4b8980ad04ed215295ea6053f0e7720ae7e00826e97bfa2cb82b5a070

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-e1071                    # [build_platform != target_platform]
    - r-lmom                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-e1071
    - r-lmom
  run:
    - r-base
    - r-e1071
    - r-lmom

test:
  commands:
    - $R -e "library('gld')"           # [not win]
    - "\"%R%\" -e \"library('gld')\""  # [win]

about:
  home: http://tolstoy.newcastle.edu.au/~rking/publ/rprogs/information.html
  license: GPL-2.0-only
  summary: The generalised lambda distribution, or Tukey lambda distribution, provides a wide variety of shapes with one functional form. This package provides random numbers, quantiles, probabilities, densities and density quantiles for four different types of the distribution, the FKML (Freimer et al 1988), RS (Ramberg
    and Schmeiser 1974), GPD (van Staden and Loots 2009) and FM5 - see documentation for details. It provides the density function, distribution function, and Quantile-Quantile plots. It implements a variety of estimation methods for the distribution, including diagnostic plots. Estimation methods include the starship (all
    4 types), method of L-Moments for the GPD and FKML types, and a number of methods for only the FKML type. These include maximum likelihood, maximum product of spacings, Titterington's method, Moments, Trimmed L-Moments and Distributional Least Absolutes.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gld
# Version: 2.6.2
# Date: 2020-01-07
# Title: Estimation and Use of the Generalised (Tukey) Lambda Distribution
# Suggests:
# Imports: stats, graphics, e1071, lmom
# Author: Robert King <Robert.King@newcastle.edu.au>, Benjamin Dean <Benjamin.Dean@uon.edu.au>, Sigbert Klinke, Paul van Staden
# Maintainer: Robert King <Robert.King@newcastle.edu.au>
# Description: The generalised lambda distribution, or Tukey lambda distribution, provides a wide variety of shapes with one functional form. This package provides random numbers, quantiles, probabilities, densities and density quantiles for four different types of the distribution, the FKML (Freimer et al 1988), RS (Ramberg and Schmeiser 1974), GPD (van Staden and Loots 2009) and FM5 - see documentation for details. It provides the density function, distribution function, and Quantile-Quantile plots. It implements a variety of estimation methods for the distribution, including diagnostic plots. Estimation methods include the starship (all 4 types), method of L-Moments for the GPD and FKML types, and a number of methods for only the FKML type. These include maximum likelihood, maximum product of spacings, Titterington's method, Moments, Trimmed L-Moments and Distributional Least Absolutes.
# License: GPL (>= 2)
# URL: http://tolstoy.newcastle.edu.au/~rking/publ/rprogs/information.html
# NeedsCompilation: yes
# Packaged: 2020-01-08 04:58:38 UTC; robertking
# Repository: CRAN
# Date/Publication: 2020-01-08 23:01:26 UTC
